blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/ViratSrivastava/A.N.T.-mk1/discussions
    about: Go to https://github.com/ViratSrivastava/A.N.T.-mk1/discussions for questions
